name: PFE_ZEINEB
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - kagglehub
  - tabulate
  - pip
  - pip:
    - mlflow==1.30.0
    - protobuf<4.0.0
