name: Train Analyse CV Pipeline

on:
  push:
    branches:
        - Test
    paths:
        - 'Notebook/Analyse CV (Catégorie)/ResumeCV.csv'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python 3.11.0
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"

      - name: Install Conda 23.5.2
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Create Conda Environment
        shell: bash -l {0}
        run: |
          source $HOME/miniconda/bin/activate
          conda init bash
          conda env create --file environment.yml --name PFE_ZEINEB
          conda install -y -c conda-forge joblib scikit-learn mlflow pandas
          
      - name: Set Up MLflow Tracking Directory
        shell: bash -l {0}
        run: |
          mkdir -p mlruns
          chmod -R 777 mlruns

      - name: Run Training Job
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns
        run: |
          conda activate PFE_ZEINEB
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          
          echo "=== Environment Debug ==="
          echo "Python path: $(which python)"
          echo "Python version: $(python --version)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "PYTHONPATH: $PYTHONPATH"
          
          echo "=== Starting Training ==="
          python Scripts/train_analyse_cv.py

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            mlruns/
            Notebook/Analyse\ CV\ \(Catégorie\)/
          retention-days: 7

      - name: Push changes to main branch
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update from training pipeline - Analyse CV" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
